GET http://localhost:8080/rest/country/all
Accept: application/json

###

GET http://localhost:8080/rest/country/0
Accept: application/json

###

GET http://localhost:8080/rest/country/filter?code=RU
Accept: application/json

###

POST http://localhost:8080/rest/country
Content-Type: application/json

{
  "id" : 12,
  "name" : "Austria",
  "codeName" : "AT"
}

###

PUT http://localhost:8080/rest/country
Content-Type: application/json

{
  "id" : 12,
  "name" : "Austria",
  "codeName" : "AT-2"
}

###

DELETE http://localhost:8080/rest/country?id=1
